# **Importing libraries and setting the enviornment to work in**

In [ ]:
!pip install pyreadstat
import pandas as pd
import pyreadstat



---

# Importing Files - **SINDH**

In [ ]:
try:
    df1, meta1 = pyreadstat.read_sav('/content/fs-sindh.sav')
    print("df loaded successfully using pyreadstat.")
    for col in df1.columns:
        print(col)

    df2, meta2 = pyreadstat.read_sav('/content/hh-sindh.sav')
    print("df loaded successfully using pyreadstat.")
    for col in df2.columns:
        print(col)

except Exception as e:
    print(f"Error loading fs-sindh.sav using pyreadstat: {e}")

df loaded successfully using pyreadstat.
HH1
HH2
LN
FS1
FS2
FS3
FSINT
FS4
FS5
FS6
FS7D
FS7M
FS7Y
FS9
FS10
FS17
FS8H
FS8M
FS11H
FS11M
FS12
FS13
FS14
FS15
FSHINT
FSFIN
CB2M
CB2Y
CB3
CB4
CB5A
CB5B
CB6
CB7
CB8A
CB8B
CB9
CB10A
CB10B
CB11
CB12A
CB12B
CB12C
CB12D
CB12X
CB12NR
CL1A
CL1B
CL1C
CL1X
CL3
CL4
CL5
CL6A
CL6B
CL6C
CL6D
CL6E
CL6X
CL7
CL8
CL9
CL10
CL11A
CL11B
CL11C
CL11D
CL11E
CL11F
CL11X
CL13
FCD2A
FCD2B
FCD2C
FCD2D
FCD2E
FCD2F
FCD2G
FCD2H
FCD2I
FCD2J
FCD2K
FCD3
FCD4
FCD5
FCF1
FCF2
FCF3
FCF6
FCF8
FCF10
FCF11
FCF12
FCF13
FCF14
FCF15
FCF16
FCF17
FCF18
FCF19
FCF20
FCF21
FCF22
FCF23
FCF24
FCF25
FCF26
PR3
PR5
PR6
PR7
PR8
PR9A
PR9B
PR10
PR11A
PR11B
PR12A
PR12B
PR12C
PR12X
PR13
PR15
FL1
FL2H
FL2M
FL3
FL4A
FL4B
FL4C
FL6A
FL6B
FL7
FL9
FL10
FL13
FL14
FL15
FL16
FL17
FL18
FLINTRO
FL19W1
FL19W2
FL19W3
FL19W4
FL19W5
FL19W6
FL19W7
FL19W8
FL19W9
FL19W10
FL19W11
FL19W12
FL19W13
FL19W14
FL19W15
FL19W16
FL19W17
FL19W18
FL19W19
FL19W20
FL19W21
FL19W22
FL19W23
FL19W24
FL19W25
FL19W26
FL19W27
FL19W28
FL19W29
FL19W30
FL19W31
FL19W32
FL19W33
FL19W34
FL19W35
FL19W36
FL19W37
FL19W38
FL19W39
FL19W40
FL19W41
FL19W42
FL19W43
FL19W44
FL19W45
FL19W46
FL19W47
FL19W48
FL19W49
FL19W50
FL19W51
FL19W52
FL19W53
FL19W54
FL19W55
FL19W56
FL19W57
FL19W58
FL19W59
FL19W60
FL19W61
FL19W62
FL19W63
FL19W64
FL19W65
FL19W66
FL19W67
FL19W68
FL19W69
FL19W70
FL19W71
FL19W72
FL20A
FL20B
FL21
FL22A
FL22B
FL22C
FL22D
FL22E
FL23A
FL23B
FL23C
FL23D
FL23E
FL23F
FL24A_o
FL24B_o
FL24C_o
FL24D_o
FL24E_o
FL25A_o
FL25B_o
FL25C_o
FL25D_o
FL25E_o
FL26
FL27A_o
FL27B_o
FL27C_o
FL27D_o
FL27E_o
FL28
HH4
HH6
HH7
HL4
ED5A
ED5B
FSAGE
FSDOI
FSDOB
division
hh7r
fselevel
fsinsurance
fsdisability
melevel
schage
HH56
fsweight
wscore
windex5
windex10
wscoreu
windex5u
windex10u
wscorer
windex5r
windex10r
FL24A
FL24B
FL24C
FL24D
FL24E
FL25A
FL25B
FL25C
FL25D
FL25E
FL27A
FL27B
FL27C
FL27D
FL27E
FL27_shift
HH52
fshweight
caretakerdis
caretakerdis2
stratum
psu
df loaded successfully using pyreadstat.
HH1
HH2
HH3
HH4
HH5D
HH5M
HH5Y
HH6
HH7
HH8
HH9
HH10
HH11H
HH11M
HH12
HH46
HH13H
HH13M
HH14
HH15
HH16
HH17
HH26A
HH26B
HH26C
HH33X$01
HH33X$02
HH33X$03
HH33X$04
HH33X$05
HH33X$06
HH33X$07
HH33X$08
HH33X$09
HH33X$10
HH33X$11
HH33X$12
HH33X$13
HH33X$14
HH33X$15
HH33X$16
HH33X$17
HH33X$18
HH33X$19
HH33X$20
HH33X$21
HH33X$22
HH33X$23
HH33X$24
HH33X$25
HH33X$26
HH33X$27
HH33X$28
HH33X$29
HH33X$30
HH33X$31
HH33X$32
HH33X$33
HH33X$34
HH33X$35
HH33X$36
HH33X$37
HH33X$38
HH33X$39
HH33X$40
HH33X$41
HH33X$42
HH33X$43
HH33X$44
HH33X$45
HH33X$46
HH33X$47
HH33X$48
HH33X$49
HH33X$50
HH33
HH39X$01
HH39X$02
HH39X$03
HH39X$04
HH39X$05
HH39X$06
HH39X$07
HH39X$08
HH39X$09
HH39X$10
HH39X$11
HH39X$12
HH39X$13
HH39X$14
HH39X$15
HH39X$16
HH39X$17
HH39X$18
HH39X$19
HH39X$20
HH39X$21
HH39X$22
HH39X$23
HH39X$24
HH39X$25
HH39X$26
HH39X$27
HH39X$28
HH39X$29
HH39X$30
HH39X$31
HH39X$32
HH39X$33
HH39X$34
HH39X$35
HH39X$36
HH39X$37
HH39X$38
HH39X$39
HH39X$40
HH39X$41
HH39X$42
HH39X$43
HH39X$44
HH39X$45
HH39X$46
HH39X$47
HH39X$48
HH39X$49
HH39X$50
HH39
HH44
HH47
HH48
HH49
HH50
HH51
HH52
INTROHL
HHAUX
HHWQ
HHFIN
HC1B
HC3
HC4
HC5
HC6
HC7A
HC7B
HC7C
HC7D
HC7E
HC7F
HC7G
HC7H
HC7I
HC7J
HC8
HC9A
HC9B
HC9C
HC9D
HC9E
HC9F
HC9G
HC9H
HC9I
HC9J
HC10A
HC10B
HC10C
HC10D
HC10E
HC10F
HC10G
HC10H
HC11
HC12
HC13
HC14
HC15
HC16
HC17
HC18A
HC18B
HC18C
HC18D
HC18E
HC18F
HC18H
HC19
ST2$1
ST2$2
ST2$3
ST2$4
ST2$5
ST2$6
ST3$1
ST3$2
ST3$3
ST3$4
ST3$5
ST3$6
ST4U$1
ST4U$2
ST4U$3
ST4U$4
ST4U$5
ST4U$6
ST4N$1
ST4N$2
ST4N$3
ST4N$4
ST4N$5
ST4N$6
EU1
EU2
EU3
EU4
EU5
EU6
EU7
EU8
EU9
TN1
TN2
WS1
WS2
WS3
WS4
WS5
WS6
WS7
WS8
WS9
WS10A
WS10B
WS10C
WS10D
WS10E
WS10F
WS10X
WS10Z
WS10NR
WS11
WS12
WS13
WS14
WS15
WS16
WS17
HW1
HW2
HW3
HW4
HW5
HW6
HW7A
HW7B
HW7C
HW7NR
SA1
SA2
WQ1
WQ2
WQ3
WQ4
WQ5D
WQ5M
WQ5Y
WQ6
WQ8
WQ31
WQ10H
WQ10M
WQ22H
WQ22M
WQ11
WQ12
WQ13
WQ14
WQ15A
WQ15B
WQ15C
WQ15D
WQ15E
WQ15F
WQ15X
WQ15Z
WQ15NR
WQ17
WQ18
WQ19
WQ20
WQ21
WQ24D
WQ24M
WQ24Y
WQ26
WQ27
WQ29
WQ25M
WQ25H
HHSEX
HHAGE
HH53
HH54
HH50A
HH55
HH56
stratum
psu
division
hh7r
helevel
wscore
windex5
windex10
wscoreu
windex5u
windex10u
wscorer
windex5r
windex10r
hhweight
wqhweight
wqsweight

In [ ]:
merged_df1 = pd.merge(df1, df2, on=['HH1', 'HH2'], how='inner')
print("Merged DataFrame info:")
merged_df1.info()
print("\nMerged DataFrame head:")
display(merged_df1.head())

merged_df1.to_csv("merged_df1.csv", index=False)

Merged DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14690 entries, 0 to 14689
Columns: 615 entries, HH1 to wqsweight
dtypes: float64(565), object(50)
memory usage: 68.9+ MB

Merged DataFrame head:

,HH1,HH2,LN,FS1,FS2,FS3,FSINT,FS4,FS5,FS6,...,windex10_y,wscoreu_y,windex5u_y,windex10u_y,wscorer_y,windex5r_y,windex10r_y,hhweight,wqhweight,wqsweight
0,1.0,2.0,3.0,1.0,2.0,3.0,103.0,2.0,103.0,101.0,...,1.0,NaN,NaN,NaN,-1.217671,1.0,1.0,1.725195,1.704734,1.613159
1,1.0,3.0,3.0,1.0,3.0,3.0,105.0,2.0,105.0,101.0,...,1.0,NaN,NaN,NaN,-0.976296,1.0,2.0,1.725195,1.704734,1.613159
2,1.0,7.0,6.0,1.0,7.0,6.0,104.0,3.0,104.0,101.0,...,1.0,NaN,NaN,NaN,-1.180770,1.0,1.0,1.725195,1.704734,1.613159
3,1.0,8.0,3.0,1.0,8.0,3.0,103.0,2.0,103.0,101.0,...,1.0,NaN,NaN,NaN,-1.415023,1.0,1.0,1.725195,1.704734,1.613159
4,1.0,9.0,3.0,1.0,9.0,3.0,105.0,2.0,105.0,101.0,...,1.0,NaN,NaN,NaN,-1.474442,1.0,1.0,1.725195,1.704734,1.613159

In [ ]:
# Make a copy of the merged DataFrame
copied_merged_df1 = merged_df1.copy()

print("Copied DataFrame info:")
copied_merged_df1.info()
print("\nCopied DataFrame head:")
display(copied_merged_df1.head())

Copied DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14690 entries, 0 to 14689
Columns: 615 entries, HH1 to wqsweight
dtypes: float64(565), object(50)
memory usage: 68.9+ MB

Copied DataFrame head:

,HH1,HH2,LN,FS1,FS2,FS3,FSINT,FS4,FS5,FS6,...,windex10_y,wscoreu_y,windex5u_y,windex10u_y,wscorer_y,windex5r_y,windex10r_y,hhweight,wqhweight,wqsweight
0,1.0,2.0,3.0,1.0,2.0,3.0,103.0,2.0,103.0,101.0,...,1.0,NaN,NaN,NaN,-1.217671,1.0,1.0,1.725195,1.704734,1.613159
1,1.0,3.0,3.0,1.0,3.0,3.0,105.0,2.0,105.0,101.0,...,1.0,NaN,NaN,NaN,-0.976296,1.0,2.0,1.725195,1.704734,1.613159
2,1.0,7.0,6.0,1.0,7.0,6.0,104.0,3.0,104.0,101.0,...,1.0,NaN,NaN,NaN,-1.180770,1.0,1.0,1.725195,1.704734,1.613159
3,1.0,8.0,3.0,1.0,8.0,3.0,103.0,2.0,103.0,101.0,...,1.0,NaN,NaN,NaN,-1.415023,1.0,1.0,1.725195,1.704734,1.613159
4,1.0,9.0,3.0,1.0,9.0,3.0,105.0,2.0,105.0,101.0,...,1.0,NaN,NaN,NaN,-1.474442,1.0,1.0,1.725195,1.704734,1.613159



---



---



---

# Imoprting files - **Punjab**

In [ ]:
try:
    df3, meta3 = pyreadstat.read_sav('/content/fs-punjab.sav')
    print("df loaded successfully using pyreadstat.")
    for col in df3.columns:
        print(col)

    df4, meta4 = pyreadstat.read_sav('/content/hh-punjab.sav')
    print("df loaded successfully using pyreadstat.")
    for col in df4.columns:
        print(col)

except Exception as e:
     print(f"Error loading file: {e}")

df loaded successfully using pyreadstat.
HH1
HH2
LN
FS1
FS2
FS3
FSINT
FS4
FS5
FS6
FS7D
FS7M
FS7Y
FS9
FS10
FS17
FS8H
FS8M
FS11H
FS11M
FS12
FS13
FS14
FS15
FSHINT
CB2M
CB2Y
CB3
CB4
CB5A
CB5B
CB6
CB7
CB8A
CB8B
CB9
CB10A
CB10B
CB11
CB12A
CB12B
CB12C
CB12D
CB12X
CB12NR
CL1A
CL1B
CL1C
CL1X
CL3
CL4
CL5
CL6A
CL6B
CL6C
CL6D
CL6E
CL6X
CL7
CL8
CL9
CL10
CL11A
CL11B
CL11C
CL11D
CL11E
CL11F
CL11X
CL13
FCD2A
FCD2B
FCD2C
FCD2D
FCD2E
FCD2F
FCD2G
FCD2H
FCD2I
FCD2J
FCD2K
FCD5
FCF1
FCF2
FCF3
FCF6
FCF8
FCF10
FCF11
FCF12
FCF13
FCF14
FCF15
FCF16
FCF17
FCF18
FCF19
FCF20
FCF21
FCF22
FCF23
FCF24
FCF25
FCF26
PR3
PR5
PR6
PR7
PR8
PR9A
PR9B
PR10
PR11A
PR11B
PR12A
PR12B
PR12C
PR12X
PR13
PR15
FL1
FL2H
FL2M
FL3
FL4A
FL4B
FL4C
FL6A
FL6B
FL7
FL9
FL10
FL13
FL14
FL15
FL16
FL17
FL18
FLINTRO
FL19W1
FL19W2
FL19W3
FL19W4
FL19W5
FL19W6
FL19W7
FL19W8
FL19W9
FL19W10
FL19W11
FL19W12
FL19W13
FL19W14
FL19W15
FL19W16
FL19W17
FL19W18
FL19W19
FL19W20
FL19W21
FL19W22
FL19W23
FL19W24
FL19W25
FL19W26
FL19W27
FL19W28
FL19W29
FL19W30
FL19W31
FL19W32
FL19W33
FL19W34
FL19W35
FL19W36
FL19W37
FL19W38
FL19W39
FL19W40
FL19W41
FL19W42
FL19W43
FL19W44
FL19W45
FL19W46
FL19W47
FL19W48
FL19W49
FL19W50
FL19W51
FL19W52
FL19W53
FL19W54
FL19W55
FL19W56
FL19W57
FL19W58
FL19W59
FL19W60
FL19W61
FL19W62
FL19W63
FL19W64
FL19W65
FL19W66
FL19W67
FL19W68
FL19W69
FL19W70
FL19W71
FL19W72
FL20A
FL20B
FL21
FL22A
FL22B
FL22C
FL22D
FL22E
FL23A
FL23B
FL23C
FL23D
FL23E
FL23F
FL24A
FL24B
FL24C
FL24D
FL24E
FL26
FL25A
FL25B
FL25C
FL25D
FL25E
FL27A
FL27B
FL27C
FL27D
FL27E
FL28
HH6
hh6r
suburban
hh7
division
HL4
ED5A
ED5B
FSAGE
FSDOI
FSDOB
HH52
HH56
fsweight
caretakerdis
wscore
windex5
windex10
wscoreu
windex5u
windex10u
wscorer
windex5r
windex10r
fselevel
fsinsurance
fsdisability
melevel
schage
fshweight
psu
stratum
df loaded successfully using pyreadstat.
HH1
HH2
HH3
HH4
HH5D
HH5M
HH5Y
HH6
HH7
HH8
HH9
HH10
HH11H
HH11M
HH12
HH46
HH13H
HH13M
HH14
HH15
HH16
HH17
HH26A
HH26B
HH26C
HH33X$01
HH33X$02
HH33X$03
HH33X$04
HH33X$05
HH33X$06
HH33X$07
HH33X$08
HH33X$09
HH33X$10
HH33X$11
HH33X$12
HH33X$13
HH33X$14
HH33X$15
HH33X$16
HH33X$17
HH33X$18
HH33X$19
HH33X$20
HH33X$21
HH33X$22
HH33X$23
HH33X$24
HH33X$25
HH33X$26
HH33X$27
HH33X$28
HH33X$29
HH33X$30
HH33X$31
HH33X$32
HH33X$33
HH33X$34
HH33X$35
HH33X$36
HH33X$37
HH33X$38
HH33X$39
HH33X$40
HH33X$41
HH33X$42
HH33X$43
HH33X$44
HH33X$45
HH33X$46
HH33X$47
HH33X$48
HH33X$49
HH33X$50
HH33
HH39X$01
HH39X$02
HH39X$03
HH39X$04
HH39X$05
HH39X$06
HH39X$07
HH39X$08
HH39X$09
HH39X$10
HH39X$11
HH39X$12
HH39X$13
HH39X$14
HH39X$15
HH39X$16
HH39X$17
HH39X$18
HH39X$19
HH39X$20
HH39X$21
HH39X$22
HH39X$23
HH39X$24
HH39X$25
HH39X$26
HH39X$27
HH39X$28
HH39X$29
HH39X$30
HH39X$31
HH39X$32
HH39X$33
HH39X$34
HH39X$35
HH39X$36
HH39X$37
HH39X$38
HH39X$39
HH39X$40
HH39X$41
HH39X$42
HH39X$43
HH39X$44
HH39X$45
HH39X$46
HH39X$47
HH39X$48
HH39X$49
HH39X$50
HH39
HH44
HH47
HH48
HH49
HH50
HH50A
HH51
HH52
HH53
HH54
HH55
HH56
INTROHL
HHAUX
HHWQ
HHFIN
HC1B
HC3
HC4
HC5
HC6
HC7A
HC7B
HC7C
HC7D
HC7E
HC7F
HC7G
HC7H
HC7I
HC7J
HC8
HC9A
HC9B
HC9C
HC9D
HC9E
HC9F
HC9G
HC9H
HC9I
HC9J
HC10A
HC10B
HC10C
HC10D
HC10E
HC10F
HC10G
HC10H
HC11
HC12
HC13
HC14
HC15
HC16
HC17
HC18A
HC18B
HC18C
HC18D
HC18E
HC18F
HC18H
HC19
ST2$1
ST2$2
ST2$3
ST2$4
ST2$5
ST2$6
ST3$1
ST3$2
ST3$3
ST3$4
ST3$5
ST3$6
ST4U$1
ST4U$2
ST4U$3
ST4U$4
ST4U$5
ST4U$6
ST4N$1
ST4N$2
ST4N$3
ST4N$4
ST4N$5
ST4N$6
RM1
RM2
RM3
RM4
EU1
EU2
EU3
EU4
EU5
EU6
EU7
EU8
EU9
WS1
WS2
WS3
WS4
WS5
WS6
WS7
WS8
WS9
WS10A
WS10B
WS10C
WS10D
WS10E
WS10F
WS10X
WS10Z
WS10NR
WS11
WS12
WS13
WS14
WS15
WS16
WS17
HW1
HW2
HW3
HW4
HW5
HW6
HW7A
HW7B
HW7NR
SA1
SA2
WQ1
WQ2
WQ3
WQ4
WQ5D
WQ5M
WQ5Y
WQ6
WQ8
WQ31
WQ10H
WQ10M
WQ22H
WQ22M
WQ11
WQ12
WQ13
WQ14
WQ15A
WQ15B
WQ15C
WQ15D
WQ15E
WQ15F
WQ15X
WQ15Z
WQ15NR
WQ16
WQ17
WQ18
WQ19
WQ20
WQ21
WQ23H
WQ23M
WQ24D
WQ24M
WQ24Y
WQ26
WQ27
WQ29
WQ25M
WQ25H
HHSEX
HHAGE
wscore
windex5
windex10
wscoreu
windex5u
windex10u
wscorer
windex5r
windex10r
HH6r
division
suburban
helevel
hhweight
wqhweight
wshweight
wqsweight
psu
stratum

In [ ]:
merged_df2 = pd.merge(df3, df4, on=['HH1', 'HH2'], how='inner')
print("Merged DataFrame info:")
merged_df2.info()
print("\nMerged DataFrame head:")
display(merged_df2.head())

Merged DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3415 entries, 0 to 3414
Columns: 601 entries, HH1 to stratum_y
dtypes: float64(567), object(34)
memory usage: 15.7+ MB

Merged DataFrame head:

,HH1,HH2,LN,FS1,FS2,FS3,FSINT,FS4,FS5,FS6,...,HH6r,division_y,suburban_y,helevel,hhweight,wqhweight,wshweight,wqsweight,psu_y,stratum_y
0,1.0,4.0,8.0,1.0,4.0,8.0,206.0,2.0,206.0,201.0,...,2.0,1.0,21.0,3.0,1.601514,1.755025,2.430788,2.430788,1.0,73.0
1,1.0,7.0,4.0,1.0,7.0,4.0,207.0,2.0,207.0,201.0,...,2.0,1.0,21.0,4.0,1.601514,1.755025,2.430788,2.430788,1.0,73.0
2,1.0,10.0,8.0,1.0,10.0,8.0,204.0,2.0,204.0,201.0,...,2.0,1.0,21.0,0.0,1.601514,1.755025,2.430788,2.430788,1.0,73.0
3,1.0,11.0,3.0,1.0,11.0,3.0,207.0,2.0,207.0,201.0,...,2.0,1.0,21.0,4.0,1.601514,1.755025,2.430788,2.430788,1.0,73.0
4,1.0,12.0,5.0,1.0,12.0,5.0,206.0,1.0,206.0,201.0,...,2.0,1.0,21.0,0.0,1.601514,1.755025,2.430788,2.430788,1.0,73.0

In [ ]:
# Make a copy of the merged DataFrame
copied_merged_df2 = merged_df2.copy()

print("Copied DataFrame info:")
copied_merged_df2.info()
print("\nCopied DataFrame head:")
display(copied_merged_df2.head())

Copied DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3415 entries, 0 to 3414
Columns: 601 entries, HH1 to stratum_y
dtypes: float64(567), object(34)
memory usage: 15.7+ MB

Copied DataFrame head:

,HH1,HH2,LN,FS1,FS2,FS3,FSINT,FS4,FS5,FS6,...,HH6r,division_y,suburban_y,helevel,hhweight,wqhweight,wshweight,wqsweight,psu_y,stratum_y
0,1.0,4.0,8.0,1.0,4.0,8.0,206.0,2.0,206.0,201.0,...,2.0,1.0,21.0,3.0,1.601514,1.755025,2.430788,2.430788,1.0,73.0
1,1.0,7.0,4.0,1.0,7.0,4.0,207.0,2.0,207.0,201.0,...,2.0,1.0,21.0,4.0,1.601514,1.755025,2.430788,2.430788,1.0,73.0
2,1.0,10.0,8.0,1.0,10.0,8.0,204.0,2.0,204.0,201.0,...,2.0,1.0,21.0,0.0,1.601514,1.755025,2.430788,2.430788,1.0,73.0
3,1.0,11.0,3.0,1.0,11.0,3.0,207.0,2.0,207.0,201.0,...,2.0,1.0,21.0,4.0,1.601514,1.755025,2.430788,2.430788,1.0,73.0
4,1.0,12.0,5.0,1.0,12.0,5.0,206.0,1.0,206.0,201.0,...,2.0,1.0,21.0,0.0,1.601514,1.755025,2.430788,2.430788,1.0,73.0



---



---



---

# Imoprting files - **KPK**

In [ ]:
try:
    df5, meta5 = pyreadstat.read_sav('/content/fs-kpk.sav')
    print("df loaded successfully using pyreadstat.")
    for col in df5.columns:
        print(col)

    df6, meta6 = pyreadstat.read_sav('/content/hh-kpk.sav')
    print("df loaded successfully using pyreadstat.")
    for col in df6.columns:
        print(col)

except Exception as e:
    print(f"Error loading fs-sindh.sav using pyreadstat: {e}")

df loaded successfully using pyreadstat.
HH1
HH2
LN
FS1
FS2
FS3
FSINT
FS4
FS5
FS6
FS7D
FS7M
FS7Y
FS9
FS10
FS17
FS8H
FS8M
FS11H
FS11M
FS12
FS13
FS14
FS15
FSHINT
FSFIN
CB2M
CB2Y
CB3
CB4
CB5A
CB5B
CB6
CB7
CB8A
CB8B
CB9
CB10A
CB10B
CB11
CB12A
CB12B
CB12C
CB12D
CB12X
CB12NR
CL1A
CL1B
CL1C
CL1X
CL3
CL4
CL5
CL6A
CL6B
CL6C
CL6D
CL6E
CL6X
CL7
CL8
CL9
CL10
CL11A
CL11B
CL11C
CL11D
CL11E
CL11F
CL11X
CL13
FCD2A
FCD2B
FCD2C
FCD2D
FCD2E
FCD2F
FCD2G
FCD2H
FCD2I
FCD2J
FCD2K
FCD3
FCD4
FCD5
FCF1
FCF2
FCF3
FCF6
FCF8
FCF10
FCF11
FCF12
FCF13
FCF14
FCF15
FCF16
FCF17
FCF18
FCF19
FCF20
FCF21
FCF22
FCF23
FCF24
FCF25
FCF26
PR3
PR5
PR6
PR7
PR8
PR9A
PR9B
PR10
PR11A
PR11B
PR12A
PR12B
PR12C
PR12X
PR13
PR15
FL1
FL2H
FL2M
FL3
FL4A
FL4B
FL4C
FL6A
FL6B
FL7
FL9
FL10
FL13
FL14
FL15
FL16
FL17
FL18
FLINTRO
FL19W1
FL19W2
FL19W3
FL19W4
FL19W5
FL19W6
FL19W7
FL19W8
FL19W9
FL19W10
FL19W11
FL19W12
FL19W13
FL19W14
FL19W15
FL19W16
FL19W17
FL19W18
FL19W19
FL19W20
FL19W21
FL19W22
FL19W23
FL19W24
FL19W25
FL19W26
FL19W27
FL19W28
FL19W29
FL19W30
FL19W31
FL19W32
FL19W33
FL19W34
FL19W35
FL19W36
FL19W37
FL19W38
FL19W39
FL19W40
FL19W41
FL19W42
FL19W43
FL19W44
FL19W45
FL19W46
FL19W47
FL19W48
FL19W49
FL19W50
FL19W51
FL19W52
FL19W53
FL19W54
FL19W55
FL19W56
FL19W57
FL19W58
FL19W59
FL19W60
FL19W61
FL19W62
FL19W63
FL19W64
FL19W65
FL19W66
FL19W67
FL19W68
FL19W69
FL19W70
FL19W71
FL19W72
FL20A
FL20B
FL21
FL22A
FL22B
FL22C
FL22D
FL22E
FL23A
FL23B
FL23C
FL23D
FL23E
FL23F
FL24A
FL24B
FL24C
FL24D
FL24E
FL25A
FL25B
FL25C
FL25D
FL25E
FL26
FL27A
FL27B
FL27C
FL27D
FL27E
FL28
HH4
HH6
HH7
HH52
HL4
ED5A
ED5B
FSAGE
FSDOI
FSDOB
melevel
fselevel
schage
fsinsurance
fsdisability
division
caretakerdis
fshweight
fsweight
wscore
windex5
windex10
wscoreu
windex5u
windex10u
wscorer
windex5r
windex10r
psu
stratum
df loaded successfully using pyreadstat.
HH1
HH2
HH3
HH4
HH5D
HH5M
HH5Y
HH6
HH7
HH8
HH9
HH10
HH11H
HH11M
HH12
HH46
HH13H
HH13M
HH14
HH15
HH16
HH17
HH26A
HH26B
HH26C
HH33X$01
HH33X$02
HH33X$03
HH33X$04
HH33X$05
HH33X$06
HH33X$07
HH33X$08
HH33X$09
HH33X$10
HH33X$11
HH33X$12
HH33X$13
HH33X$14
HH33X$15
HH33X$16
HH33X$17
HH33X$18
HH33X$19
HH33X$20
HH33X$21
HH33X$22
HH33X$23
HH33X$24
HH33X$25
HH33X$26
HH33X$27
HH33X$28
HH33X$29
HH33X$30
HH33X$31
HH33X$32
HH33X$33
HH33X$34
HH33X$35
HH33X$36
HH33X$37
HH33X$38
HH33X$39
HH33X$40
HH33X$41
HH33X$42
HH33X$43
HH33X$44
HH33X$45
HH33X$46
HH33X$47
HH33X$48
HH33X$49
HH33X$50
HH33
HH39X$01
HH39X$02
HH39X$03
HH39X$04
HH39X$05
HH39X$06
HH39X$07
HH39X$08
HH39X$09
HH39X$10
HH39X$11
HH39X$12
HH39X$13
HH39X$14
HH39X$15
HH39X$16
HH39X$17
HH39X$18
HH39X$19
HH39X$20
HH39X$21
HH39X$22
HH39X$23
HH39X$24
HH39X$25
HH39X$26
HH39X$27
HH39X$28
HH39X$29
HH39X$30
HH39X$31
HH39X$32
HH39X$33
HH39X$34
HH39X$35
HH39X$36
HH39X$37
HH39X$38
HH39X$39
HH39X$40
HH39X$41
HH39X$42
HH39X$43
HH39X$44
HH39X$45
HH39X$46
HH39X$47
HH39X$48
HH39X$49
HH39X$50
HH39
HH44
HH47
HH48
HH49
HH50
HH50A
HH51
HH52
HH53
HH54
HH55
HH56
INTROHL
HHAUX
HHWQ
HHFIN
HC1B
HC3
HC4
HC5
HC6
HC7A
HC7B
HC7C
HC7D
HC7E
HC7F
HC7G
HC7H
HC7I
HC7J
HC8
HC9A
HC9B
HC9C
HC9D
HC9E
HC9F
HC9G
HC9H
HC9I
HC9J
HC10A
HC10B
HC10C
HC10D
HC10E
HC10F
HC10G
HC10H
HC11
HC12
HC13
HC14
HC15
HC16
HC17
HC18A
HC18B
HC18C
HC18D
HC18E
HC18F
HC18H
HC19
ST2$1
ST2$2
ST2$3
ST2$4
ST2$5
ST2$6
ST3$1
ST3$2
ST3$3
ST3$4
ST3$5
ST3$6
ST4U$1
ST4U$2
ST4U$3
ST4U$4
ST4U$5
ST4U$6
ST4N$1
ST4N$2
ST4N$3
ST4N$4
ST4N$5
ST4N$6
EU1
EU2
EU3
EU4
EU5
EU6
EU7
EU8
EU9
WS1
WS2
WS3
WS4
WS5
WS6
WS7
WS8
WS9
WS10A
WS10B
WS10C
WS10D
WS10E
WS10F
WS10X
WS10Z
WS10NR
WS11
WS12
WS13
WS14
WS15
WS16
WS17
HW1
HW2
HW3
HW4
HW5
HW6
HW7A
HW7B
HW7C
HW7NR
SA1
SA2
WQ1
WQ2
WQ3
WQ4
WQ5D
WQ5M
WQ5Y
WQ6
WQ8
WQ31
WQ10H
WQ10M
WQ22H
WQ22M
WQ11
WQ12
WQ13
WQ14
WQ15A
WQ15B
WQ15C
WQ15D
WQ15E
WQ15F
WQ15X
WQ15Z
WQ15NR
WQ17
WQ18
WQ19
WQ20
WQ21
WQ24D
WQ24M
WQ24Y
WQ26
WQ27
WQ29
WQ25M
WQ25H
HHSEX
HHAGE
hhweight
wqhweight
wqsweight
division
helevel
wscore
windex5
windex10
wscoreu
windex5u
windex10u
wscorer
windex5r
windex10r
psu
stratum

In [ ]:
merged_df3 = pd.merge(df5, df6, on=['HH1', 'HH2'], how='inner')
print("Merged DataFrame info:")
merged_df3.info()
print("\nMerged DataFrame head:")
display(merged_df3.head())

Merged DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19379 entries, 0 to 19378
Columns: 593 entries, HH1 to stratum_y
dtypes: float64(558), object(35)
memory usage: 87.7+ MB

Merged DataFrame head:

,HH1,HH2,LN,FS1,FS2,FS3,FSINT,FS4,FS5,FS6,...,windex5_y,windex10_y,wscoreu_y,windex5u_y,windex10u_y,wscorer_y,windex5r_y,windex10r_y,psu_y,stratum_y
0,1.0,1.0,5.0,1.0,1.0,5.0,2003.0,2.0,2003.0,2001.0,...,5.0,10.0,1.385519,5.0,10.0,NaN,NaN,NaN,1.0,1.0
1,1.0,3.0,5.0,1.0,3.0,5.0,2003.0,3.0,2003.0,2001.0,...,5.0,10.0,0.924569,5.0,9.0,NaN,NaN,NaN,1.0,1.0
2,1.0,4.0,5.0,1.0,4.0,5.0,2005.0,2.0,2005.0,2001.0,...,5.0,10.0,1.233741,5.0,10.0,NaN,NaN,NaN,1.0,1.0
3,1.0,5.0,4.0,1.0,5.0,4.0,2003.0,3.0,2003.0,2001.0,...,5.0,9.0,0.526319,4.0,7.0,NaN,NaN,NaN,1.0,1.0
4,1.0,8.0,10.0,1.0,8.0,10.0,2004.0,8.0,2004.0,2001.0,...,5.0,10.0,0.579965,4.0,7.0,NaN,NaN,NaN,1.0,1.0

In [ ]:
# Make a copy of the merged DataFrame
copied_merged_df3 = merged_df3.copy()

print("Copied DataFrame info:")
copied_merged_df3.info()
print("\nCopied DataFrame head:")
display(copied_merged_df3.head())

Copied DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19379 entries, 0 to 19378
Columns: 593 entries, HH1 to stratum_y
dtypes: float64(558), object(35)
memory usage: 87.7+ MB

Copied DataFrame head:

,HH1,HH2,LN,FS1,FS2,FS3,FSINT,FS4,FS5,FS6,...,windex5_y,windex10_y,wscoreu_y,windex5u_y,windex10u_y,wscorer_y,windex5r_y,windex10r_y,psu_y,stratum_y
0,1.0,1.0,5.0,1.0,1.0,5.0,2003.0,2.0,2003.0,2001.0,...,5.0,10.0,1.385519,5.0,10.0,NaN,NaN,NaN,1.0,1.0
1,1.0,3.0,5.0,1.0,3.0,5.0,2003.0,3.0,2003.0,2001.0,...,5.0,10.0,0.924569,5.0,9.0,NaN,NaN,NaN,1.0,1.0
2,1.0,4.0,5.0,1.0,4.0,5.0,2005.0,2.0,2005.0,2001.0,...,5.0,10.0,1.233741,5.0,10.0,NaN,NaN,NaN,1.0,1.0
3,1.0,5.0,4.0,1.0,5.0,4.0,2003.0,3.0,2003.0,2001.0,...,5.0,9.0,0.526319,4.0,7.0,NaN,NaN,NaN,1.0,1.0
4,1.0,8.0,10.0,1.0,8.0,10.0,2004.0,8.0,2004.0,2001.0,...,5.0,10.0,0.579965,4.0,7.0,NaN,NaN,NaN,1.0,1.0



---



---



---

In [ ]:
try:
    df7, meta7 = pyreadstat.read_sav('/content/fs-balochistan.sav')
    print("df loaded successfully using pyreadstat.")
    for col in df7.columns:
        print(col)

    df8, meta8 = pyreadstat.read_sav('/content/hh-balochistan.sav')
    print("df loaded successfully using pyreadstat.")
    for col in df8.columns:
        print(col)

except Exception as e:
    print(f"Error loading fs-sindh.sav using pyreadstat: {e}")

df loaded successfully using pyreadstat.
HH1
HH2
LN
FS1
FS2
FS3
FSINT
FS4
FS5
FS6
FS7D
FS7M
FS7Y
FS9
FS10
FS17
FS8H
FS8M
FS11H
FS11M
FS12
FS13
FS14
FS15
FSHINT
FSFIN
CB2M
CB2Y
CB3
CB4
CB5A
CB5B
CB6
CB7
CB8A
CB8B
CB9
CB10A
CB10B
CB11
CB12A
CB12B
CB12C
CB12D
CB12X
CB12NR
CL1A
CL1B
CL1C
CL1X
CL3
CL4
CL5
CL6A
CL6B
CL6C
CL6D
CL6E
CL6X
CL7
CL8
CL9
CL10
CL11A
CL11B
CL11C
CL11D
CL11E
CL11F
CL11X
CL13
FCD2A
FCD2B
FCD2C
FCD2D
FCD2E
FCD2F
FCD2G
FCD2H
FCD2I
FCD2J
FCD2K
FCD3
FCD4
FCD5
FCF1
FCF2
FCF3
FCF6
FCF8
FCF10
FCF11
FCF12
FCF13
FCF14
FCF15
FCF16
FCF17
FCF18
FCF19
FCF20
FCF21
FCF22
FCF23
FCF24
FCF25
FCF26
PR3
PR5
PR6
PR7
PR8
PR9A
PR9B
PR10
PR11A
PR11B
PR12A
PR12B
PR12C
PR12X
PR13
PR15
FL1
FL2H
FL2M
FL3
FL4A
FL4B
FL4C
FL6A
FL6B
FL7
FL9
FL10
FL13
FL14
FL15
FL16
FL17
FL18
FLINTRO
FL19W1
FL19W2
FL19W3
FL19W4
FL19W5
FL19W6
FL19W7
FL19W8
FL19W9
FL19W10
FL19W11
FL19W12
FL19W13
FL19W14
FL19W15
FL19W16
FL19W17
FL19W18
FL19W19
FL19W20
FL19W21
FL19W22
FL19W23
FL19W24
FL19W25
FL19W26
FL19W27
FL19W28
FL19W29
FL19W30
FL19W31
FL19W32
FL19W33
FL19W34
FL19W35
FL19W36
FL19W37
FL19W38
FL19W39
FL19W40
FL19W41
FL19W42
FL19W43
FL19W44
FL19W45
FL19W46
FL19W47
FL19W48
FL19W49
FL19W50
FL19W51
FL19W52
FL19W53
FL19W54
FL19W55
FL19W56
FL19W57
FL19W58
FL19W59
FL19W60
FL19W61
FL19W62
FL19W63
FL19W64
FL19W65
FL19W66
FL19W67
FL19W68
FL19W69
FL19W70
FL19W71
FL19W72
FL20A
FL20B
FL21
FL22A
FL22B
FL22C
FL22D
FL22E
FL23A
FL23B
FL23C
FL23D
FL23E
FL23F
FL26
FL28
HH4
HH6
HH7
HH52
HL4
ED5A
ED5B
FSAGE
FSDOI
FSDOB
FL24A
FL24B
FL24C
FL24D
FL24E
FL25A
FL25B
FL25C
FL25D
FL25E
FL27A
FL27B
FL27C
FL27D
FL27E
melevel
fselevel
schage
fsinsurance
fsdisability
division
hh7r
caretakerdis
fshweight
fsweight
wscore
windex5
windex10
wscoreu
windex5u
windex10u
wscorer
windex5r
windex10r
psu
stratum
df loaded successfully using pyreadstat.
HH1
HH2
HH3
HH4
HH5D
HH5M
HH5Y
HH6
HH7
HH8
HH9
HH10
HH11H
HH11M
HH12
HH46
HH13H
HH13M
HH14
HH15
HH16
HH17
HH26A
HH26B
HH26C
HH33X$01
HH33X$02
HH33X$03
HH33X$04
HH33X$05
HH33X$06
HH33X$07
HH33X$08
HH33X$09
HH33X$10
HH33X$11
HH33X$12
HH33X$13
HH33X$14
HH33X$15
HH33X$16
HH33X$17
HH33X$18
HH33X$19
HH33X$20
HH33X$21
HH33X$22
HH33X$23
HH33X$24
HH33X$25
HH33X$26
HH33X$27
HH33X$28
HH33X$29
HH33X$30
HH33X$31
HH33X$32
HH33X$33
HH33X$34
HH33X$35
HH33X$36
HH33X$37
HH33X$38
HH33X$39
HH33X$40
HH33X$41
HH33X$42
HH33X$43
HH33X$44
HH33X$45
HH33X$46
HH33X$47
HH33X$48
HH33X$49
HH33X$50
HH33
HH39X$01
HH39X$02
HH39X$03
HH39X$04
HH39X$05
HH39X$06
HH39X$07
HH39X$08
HH39X$09
HH39X$10
HH39X$11
HH39X$12
HH39X$13
HH39X$14
HH39X$15
HH39X$16
HH39X$17
HH39X$18
HH39X$19
HH39X$20
HH39X$21
HH39X$22
HH39X$23
HH39X$24
HH39X$25
HH39X$26
HH39X$27
HH39X$28
HH39X$29
HH39X$30
HH39X$31
HH39X$32
HH39X$33
HH39X$34
HH39X$35
HH39X$36
HH39X$37
HH39X$38
HH39X$39
HH39X$40
HH39X$41
HH39X$42
HH39X$43
HH39X$44
HH39X$45
HH39X$46
HH39X$47
HH39X$48
HH39X$49
HH39X$50
HH39
HH44
HH47
HH48
HH49
HH50
HH50A
HH51
HH52
HH53
HH54
HH55
HH56
INTROHL
HHAUX
HHWQ
HHFIN
HC1B
HC3
HC4
HC5
HC6
HC7A
HC7B
HC7C
HC7D
HC7E
HC7F
HC7G
HC7H
HC7I
HC7J
HC8
HC9A
HC9B
HC9C
HC9D
HC9E
HC9F
HC9G
HC9H
HC9I
HC9J
HC10A
HC10B
HC10C
HC10D
HC10E
HC10F
HC10G
HC10H
HC11
HC12
HC13
HC14
HC15
HC16
HC17
HC18A
HC18B
HC18C
HC18D
HC18E
HC18F
HC18H
HC19
ST2$1
ST2$2
ST2$3
ST2$4
ST2$5
ST2$6
ST3$1
ST3$2
ST3$3
ST3$4
ST3$5
ST3$6
ST4U$1
ST4U$2
ST4U$3
ST4U$4
ST4U$5
ST4U$6
ST4N$1
ST4N$2
ST4N$3
ST4N$4
ST4N$5
ST4N$6
EU1
EU2
EU3
EU4
EU5
EU6
EU7
EU8
EU9
TN1
TN2
WS1
WS2
WS3
WS4
WS5
WS6
WS7
WS8
WS9
WS10A
WS10B
WS10C
WS10D
WS10E
WS10F
WS10X
WS10Z
WS10NR
WS11
WS12
WS13
WS14
WS15
WS16
WS17
HW1
HW2
HW3
HW4
HW5
HW6
HW7A
HW7B
HW7C
HW7NR
SA1
SA2
WQ1
WQ2
WQ3
WQ4
WQ5D
WQ5M
WQ5Y
WQ6
WQ8
WQ31
WQ10H
WQ10M
WQ22H
WQ22M
WQ11
WQ12
WQ13
WQ14
WQ15A
WQ15B
WQ15C
WQ15D
WQ15E
WQ15F
WQ15X
WQ15Z
WQ15NR
WQ17
WQ18
WQ19
WQ20
WQ21
WQ24D
WQ24M
WQ24Y
WQ26
WQ27
WQ29
WQ25M
WQ25H
HHSEX
HHAGE
division
hh7r
helevel
hhweight
wqhweight
wqsweight
wscore
windex5
windex10
wscoreu
windex5u
windex10u
wscorer
windex5r
windex10r
psu
stratum

In [ ]:
merged_df4 = pd.merge(df7, df8, on=['HH1', 'HH2'], how='inner')
print("Merged DataFrame info:")
merged_df4.info()
print("\nMerged DataFrame head:")
display(merged_df4.head())

Merged DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Columns: 597 entries, HH1 to stratum_y
dtypes: float64(562), object(35)
memory usage: 79.9+ MB

Merged DataFrame head:

,HH1,HH2,LN,FS1,FS2,FS3,FSINT,FS4,FS5,FS6,...,windex5_y,windex10_y,wscoreu_y,windex5u_y,windex10u_y,wscorer_y,windex5r_y,windex10r_y,psu_y,stratum_y
0,1.0,1.0,3.0,1.0,1.0,3.0,104.0,2.0,104.0,101.0,...,2.0,4.0,NaN,NaN,NaN,-0.073337,3.0,5.0,1.0,33.0
1,1.0,4.0,3.0,1.0,4.0,3.0,103.0,2.0,103.0,101.0,...,1.0,2.0,NaN,NaN,NaN,-0.794960,1.0,2.0,1.0,33.0
2,1.0,5.0,5.0,1.0,5.0,5.0,104.0,2.0,104.0,101.0,...,1.0,1.0,NaN,NaN,NaN,-1.038756,1.0,2.0,1.0,33.0
3,1.0,6.0,4.0,1.0,6.0,4.0,102.0,2.0,102.0,101.0,...,1.0,2.0,NaN,NaN,NaN,-0.919338,1.0,2.0,1.0,33.0
4,1.0,8.0,3.0,1.0,8.0,3.0,103.0,2.0,103.0,101.0,...,1.0,2.0,NaN,NaN,NaN,-0.637231,2.0,3.0,1.0,33.0

In [ ]:
# Make a copy of the merged DataFrame
copied_merged_df4 = merged_df4.copy()

print("Copied DataFrame info:")
copied_merged_df4.info()
print("\nCopied DataFrame head:")
display(copied_merged_df4.head())

Copied DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Columns: 597 entries, HH1 to stratum_y
dtypes: float64(562), object(35)
memory usage: 79.9+ MB

Copied DataFrame head:

,HH1,HH2,LN,FS1,FS2,FS3,FSINT,FS4,FS5,FS6,...,windex5_y,windex10_y,wscoreu_y,windex5u_y,windex10u_y,wscorer_y,windex5r_y,windex10r_y,psu_y,stratum_y
0,1.0,1.0,3.0,1.0,1.0,3.0,104.0,2.0,104.0,101.0,...,2.0,4.0,NaN,NaN,NaN,-0.073337,3.0,5.0,1.0,33.0
1,1.0,4.0,3.0,1.0,4.0,3.0,103.0,2.0,103.0,101.0,...,1.0,2.0,NaN,NaN,NaN,-0.794960,1.0,2.0,1.0,33.0
2,1.0,5.0,5.0,1.0,5.0,5.0,104.0,2.0,104.0,101.0,...,1.0,1.0,NaN,NaN,NaN,-1.038756,1.0,2.0,1.0,33.0
3,1.0,6.0,4.0,1.0,6.0,4.0,102.0,2.0,102.0,101.0,...,1.0,2.0,NaN,NaN,NaN,-0.919338,1.0,2.0,1.0,33.0
4,1.0,8.0,3.0,1.0,8.0,3.0,103.0,2.0,103.0,101.0,...,1.0,2.0,NaN,NaN,NaN,-0.637231,2.0,3.0,1.0,33.0

appended punjab and sindh,,, appending kpk and balochistan

In [ ]:

sindhpunjab_df = pd.concat([copied_merged_df1, copied_merged_df2], ignore_index=True)
print("\nappended DataFrame info:")
sindhpunjab_df.info()
print("\nappended DataFrame head:")
display(sindhpunjab_df.head())

appended DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18105 entries, 0 to 18104
Columns: 630 entries, HH1 to wshweight
dtypes: float64(580), object(50)
memory usage: 87.0+ MB

appended DataFrame head:

,HH1,HH2,LN,FS1,FS2,FS3,FSINT,FS4,FS5,FS6,...,RM1,RM2,RM3,RM4,WQ16,WQ23H,WQ23M,HH6r,suburban_y,wshweight
0,1.0,2.0,3.0,1.0,2.0,3.0,103.0,2.0,103.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,3.0,3.0,1.0,3.0,3.0,105.0,2.0,105.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,7.0,6.0,1.0,7.0,6.0,104.0,3.0,104.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,8.0,3.0,1.0,8.0,3.0,103.0,2.0,103.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,9.0,3.0,1.0,9.0,3.0,105.0,2.0,105.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sindhpunjab_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18105 entries, 0 to 18104
Columns: 630 entries, HH1 to wshweight
dtypes: float64(580), object(50)
memory usage: 87.0+ MB

In [ ]:

kpkbaloch_df = pd.concat([copied_merged_df3, copied_merged_df4], ignore_index=True)
print("\nappended DataFrame info:")
kpkbaloch_df.info()
print("\nappended DataFrame head:")
display(kpkbaloch_df.head())

sindhpunjab_df.info()

kpkbaloch_df.to_excel("kpkbaloch.xlsx", index = False)

# ***cleaning***

In [ ]:
# Define the list of columns to keep
columns_to_keep = [
    'HH1', 'HH2',  # Merge keys
    'FSAGE_x',  # Age of child (continuous)
    'FS2_x',    # Gender of child (male/female dummy, assuming 1=male, 2=female) - need to confirm mapping
    'HH52_x',# Birth order / number of siblings (optional) - Need to identify this variable
    'melevel_x', # Mother's education (categorical)
    'hh7r_y',   # Household Head's education (categorical)
    'windex5_y', # Household wealth index quintile
    'HH6_y',    # Household size (total members)
    'HH4_y',    # Head of household's sex (female-headed vs male-headed)
    'CB7_x',  #(Attended school or early childhood programme during current school year)
    'CB4_x',  #(Ever attended school): Broader measure; can be used for robustness check.
    'CB9_x',  # (Attended during previous year): Can show persistence
]

# Filter the DataFrame to keep only the specified columns
cleaned_df1 = copied_merged_df1[columns_to_keep].copy()

print("Cleaned DataFrame info:")
cleaned_df1.info()
print("\nCleaned DataFrame head:")
display(cleaned_df1.head())

In [ ]:
cleaned_df1.isna().sum()
cleaned_df1.to_excel("sindh.xlsx", index = False)